### ISSUE TITLE
which micro sd socket

### ISSUE THREAD

**Issue by tomse** [ztto/ArdSCSino-stm32#1]
Thanks a lot for creating this.

I have a question, which micro sd socket is it (vendor product), as I've found quite a lot different
but none of them have the legs in their right position compared to your pcb.

cheers

**Comment by ztto** [comment]
ArdSCSino.ino is a Micro SD TF card memory shield module compatible with Arduino SPI Micro SD Adapter 6PIN. ArdSCSinoV2.ino is Hirose DM3AT-SF-PEJM5.

**Comment by tomse** [comment]
I should have been specific in mentioning v2, but you answered for both, thanks a lot :-D
