### ISSUE TITLE
3v3 tolerant pins used ?

### ISSUE THREAD

**Issue by penfold42** [ztto/ArdSCSino-stm32#2]
It looks like SCSI C/D and DBP are using non-5v tolerant pins.

Is this a problem ?

**Comment by ztto** [comment]
Thank you very much. There is a problem. Change the PIN arrangement.

**Comment by penfold42** [comment]
Actually, on second thoughts it might be OK.

https://www.analog.com/media/en/reference-design-documentation/design-notes/dn034f.pdf

If I’m reading  this right, passive terminators will let  the voltage idle at 5*330/550V which is 3v.
It’s an open collector bus so nothing should ever actually put 5V on the bus pins.

For safety I’d recommend clamping diodes you prevent the signals exceeding 3.3v

**Comment by ztto** [comment]
it is working at the moment, but there is also 5VPIN so I am thinking to switch to that

**Comment by penfold42** [comment]
I’m laying out a board right now on kicad that will have provision for termination resistors.

Should I hold off publishing and making it ?

**Comment by ztto** [comment]
PIN placement can be switched by definition, it takes time to switch, so I think it is not necessary to refrain from creating
