### ISSUE TITLE
Build time compiler errors

### ISSUE THREAD

**Issue by JoNilsson** [ztto/ArdSCSino-stm32#5]
`ArdSCSinoV2`

Environment:
Arduino IDE v1.8.12
STM32 Cores v1.9.0
SdFat v1.1.4

Getting the following compile error:

```
ArdSCSinoV2:34:17: error: no matching function for call to 'SPIClass::SPIClass(int)'
   34 | SPIClass SPI_1(1);
      |                 ^
In file included from ~/Arduino/libraries/SdFat/src/SysCall.h:33,
                 from ~/Arduino/libraries/SdFat/src/SdFat.h:31,
                 from ~/ArdSCSino-stm32/ArdSCSinoV2/ArdSCSinoV2.ino:28:
```

Suspicion; STM Cores may be newer than what was intended to be used?  

☠️

**Comment by ztto** [comment]
tools -> board -> Boards Manager -> Filter your search
Find and install "Arduino SAM Boards (32-bits ARM Cortex-M3)" 
select board "Generic STM32F103C series"

**Comment by JoNilsson** [comment]
![image](https://user-images.githubusercontent.com/54599325/86451760-39f81300-bcd0-11ea-9d11-4227906ac398.png)

![image](https://user-images.githubusercontent.com/54599325/86451810-48dec580-bcd0-11ea-8134-d7da18f1d1c5.png)

`"Arduino SAM Boards (32-bits ARM Cortex-M3)"` does not include profiles for `STM32F103C` boards.   
These board profile are included in `"STM32 Cores"`  

furthermore, have the correct board selected.  `"Generic STM32F1 Series"`
specifically `"BluePill F103C8"`

The compile error remains:
```
ArdSCSinoV2:34:17: error: no matching function for call to 'SPIClass::SPIClass(int)'
   34 | SPIClass SPI_1(1);
      |                 ^
In file included from~/Arduino/libraries/SdFat/src/SysCall.h:33,
                 from ~/Arduino/libraries/SdFat/src/SdFat.h:31,
                 from ~/ArdSCSino-stm32/ArdSCSinoV2/ArdSCSinoV2.ino:28:
~/Arduino15/packages/STM32/hardware/stm32/1.9.0/libraries/SPI/src/SPI.h:117:5: note: candidate: 'SPIClass::SPIClass(uint8_t, uint8_t, uint8_t, uint8_t)'
```
34 [`SPIClass SPI_1(1);`](https://github.com/ztto/ArdSCSino-stm32/blob/c062ff8c1bf96e53f02739f2e31cb8654d09d7c6/ArdSCSinoV2.ino#L34)

**Comment by ztto** [comment]
https://github.com/rogerclarkmelbourne/Arduino_STM32

**Comment by JoNilsson** [comment]
That seems to have gotten me past that original `SPIClass` error.   I guess you can close the issue now.  

However, this just opened up a pandoras box of new formatting errors in the SdFat lib... most of them stemming from   `/Arduino/libraries/SdFat/src/FatLib/istream.h`  
... ( ͡° ʖ̯ ͡°)  

Full error log here: https://gist.github.com/JoNilsson/ffee2534ecc5976409e2c4734d6a2b91
  
Super sad can't get the project to compile!  maybe you hook us up with a binary or hex of the compiled firmware?

**Comment by JoNilsson** [comment]
Looking deeper into SdFat, where the majority of my compilation errors seem to be stemming from, I realize that the Lib is highly configurable.  Possibly, you have customized `SdFatConfig.h`?

**Comment by ztto** [comment]
https://github.com/rogerclarkmelbourne/Arduino_STM32/releases/tag/v1.0.0

**Comment by JoNilsson** [comment]
![image](https://user-images.githubusercontent.com/54599325/86520192-905f7180-bdf6-11ea-8882-44591d4ac6fa.png)
Closing issue now.  
Thanks for the insights.
